# Generated by Django 3.2 on 2022-03-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='code',
        ),
        migrations.AddField(
            model_name='address',
            name='flat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='house',
            field=models.CharField(default=-1, max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(default=-1),
        ),
    ]
